#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-4d =						\
	papers/4d/packages.tex					\
	papers/4d/main.tex					\
	papers/4d/references.bib				\
	papers/4d/teil0.tex					\
	papers/4d/teil1.tex					\
	papers/4d/teil2.tex					\
	papers/4d/teil3.tex

