#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-mongekant =						\
	papers/mongekant/packages.tex					\
	papers/mongekant/main.tex					\
	papers/mongekant/references.bib				\
	papers/mongekant/teil0.tex					\
	papers/mongekant/teil1.tex					\
	papers/mongekant/teil2.tex					\
	papers/mongekant/teil3.tex

