#
# Makefile.inc
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/020-koordinaten/1-koordinaten.tex			\
	chapters/020-koordinaten/2-tangentialvektoren.tex		\
	chapters/020-koordinaten/3-differentialoperatoren.tex		\
	chapters/020-koordinaten/4-diffmannig.tex			\
	chapters/020-koordinaten/chapter
