#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-wirbelringe =						\
	papers/wirbelringe/packages.tex					\
	papers/wirbelringe/main.tex					\
	papers/wirbelringe/references.bib				\
	papers/wirbelringe/bewegung.tex					\
	papers/wirbelringe/helmholtz.tex					\
	papers/wirbelringe/slugModell.tex					\
	papers/wirbelringe/Wirbelschleppe.tex					\
	papers/wirbelringe/WirbelringKanone.tex

