#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-wirbelringe =						\
	papers/wirbelringe/packages.tex					\
	papers/wirbelringe/main.tex					\
	papers/wirbelringe/references.bib				\
	papers/wirbelringe/teil0.tex					\
	papers/wirbelringe/teil1.tex					\
	papers/wirbelringe/teil2.tex					\
	papers/wirbelringe/teil3.tex

