#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-geoalgebra =						\
	papers/geoalgebra/packages.tex					\
	papers/geoalgebra/main.tex					\
	papers/geoalgebra/references.bib				\
	papers/geoalgebra/bivektoren.tex				\
	papers/geoalgebra/einleitung.tex				\
	papers/geoalgebra/komplexe-zahlen.tex				\
	papers/geoalgebra/wedge-produkt.tex
