#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-geoalgebra =						\
	papers/geoalgebra/packages.tex					\
	papers/geoalgebra/main.tex					\
	papers/geoalgebra/references.bib				\
	papers/geoalgebra/teil0.tex					\
	papers/geoalgebra/teil1.tex					\
	papers/geoalgebra/teil2.tex					\
	papers/geoalgebra/teil3.tex

