#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/070-hodge/1-hodge.tex					\
	chapters/070-hodge/2-koordinatenfrei.tex			\
	chapters/070-hodge/3-vektoranalysis.tex				\
	chapters/070-hodge/4-kodifferential.tex				\
	chapters/070-hodge/5-laplace.tex				\
	chapters/070-hodge/uebungsaufgaben/701.tex			\
	chapters/070-hodge/chapter.tex
