#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/000-einleitung/1-feldbegriff.tex			\
	chapters/000-einleitung/2-mathematik.tex			\
	chapters/000-einleitung/3-buch.tex				\
	chapters/000-einleitung/4-quellen.tex				\
	chapters/000-einleitung/chapter.tex
