#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-particles =						\
	papers/particles/packages.tex					\
	papers/particles/main.tex					\
	papers/particles/references.bib				\
	papers/particles/teil1*.tex					\
	papers/particles/teil2*.tex					\
	papers/particles/teil3*.tex

