#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-reaktdiff =						\
	papers/reaktdiff/packages.tex					\
	papers/reaktdiff/main.tex					\
	papers/reaktdiff/references.bib				\
	papers/reaktdiff/teil0.tex					\
	papers/reaktdiff/teil1.tex					\
	papers/reaktdiff/teil2.tex					\
	papers/reaktdiff/teil3.tex

