#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter5 =								\
	../slides/5/gauss.tex						\
	../slides/5/schnittkruemmung.tex				\
	../slides/5/gradrot.tex						\
	../slides/5/kont.tex						\
	../slides/5/algebra.tex

