#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-openfoam =						\
	papers/openfoam/packages.tex					\
	papers/openfoam/main.tex					\
	papers/openfoam/references.bib				\
	papers/openfoam/teil0.tex					\
	papers/openfoam/teil1.tex					\
	papers/openfoam/teil2.tex					\
	papers/openfoam/teil3.tex

