#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-reynolds =						\
	papers/reynolds/packages.tex					\
	papers/reynolds/main.tex					\
	papers/reynolds/references.bib				\
	papers/reynolds/teil0.tex					\
	papers/reynolds/teil1.tex					\
	papers/reynolds/teil2.tex					\
	papers/reynolds/teil3.tex

