#
# Makefile.inc
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/050-gauss/1-gauss3d.tex				\
	chapters/050-gauss/2-gauss.tex					\
	chapters/050-gauss/3-erhaltungssatz.tex				\
	chapters/050-gauss/chapter.tex
