#
# Makefile -- build images
#
# (c) 2025 Prof Dr Andreas Müller
#
all:									\
	fourier.pdf							\
	strahlung.pdf							\
	federpendel.pdf

fourier.pdf:	fourier.tex
	pdflatex fourier.tex

strahlung.pdf:	strahlung.tex
	pdflatex strahlung.tex

federpendel.pdf:	federpendel.tex
	pdflatex federpendel.tex

