#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/010-fallstudie/1-temperatur.tex			\
	chapters/010-fallstudie/2-waermekapazitaet.tex			\
	chapters/010-fallstudie/3-waermefluss.tex			\
	chapters/010-fallstudie/4-prinzipal.tex				\
	chapters/010-fallstudie/chapter
