#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-nerven =						\
	papers/nerven/packages.tex					\
	papers/nerven/main.tex					\
	papers/nerven/references.bib				\
	papers/nerven/teil0.tex					\
	papers/nerven/teil1.tex					\
	papers/nerven/teil2.tex					\
	papers/nerven/teil3.tex

