#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ueberschall =						\
	papers/ueberschall/packages.tex					\
	papers/ueberschall/main.tex					\
	papers/ueberschall/references.bib				\
	papers/ueberschall/teil0.tex					\
	papers/ueberschall/teil1.tex					\
	papers/ueberschall/teil2.tex					\
	papers/ueberschall/teil3.tex

