#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter7 =								\
	../slides/7/paralleltransport.tex				\
	../slides/7/kartesisch.tex					\
	../slides/7/polar.tex						\
	../slides/7/kugel.tex	

