#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/080-feldgleichungen/1-waerme.tex			\
	chapters/080-feldgleichungen/2-wellen.tex			\
	chapters/080-feldgleichungen/3-loesung.tex			\
	chapters/080-feldgleichungen/4-annahmen.tex			\
	chapters/080-feldgleichungen/chapter.tex
