#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-maxwell =							\
	papers/maxwell/packages.tex					\
	papers/maxwell/main.tex						\
	papers/maxwell/references.bib					\
	papers/maxwell/Geschichte_und_Einfuehrung.tex					\
	papers/maxwell/teil1.tex					\
	papers/maxwell/df.tex					\
	papers/maxwell/InhomogeneMaxwellgleichungen.tex\


