#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/090-pdenumerik/1-fdm.tex				\
	chapters/090-pdenumerik/2-fvm.tex				\
	chapters/090-pdenumerik/3-fem.tex				\
	chapters/090-pdenumerik/4-spektral.tex				\
	chapters/090-pdenumerik/5-linear.tex				\
	chapters/090-pdenumerik/chapter.tex
