#
# Makefile.inc
#
# (c) 2025 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/060-pformen/1-pformen.tex				\
	chapters/060-pformen/2-differential.tex				\
	chapters/060-pformen/3-abbildungen.tex				\
	chapters/060-pformen/4-poincare.tex				\
	chapters/060-pformen/chapter.tex
