#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-neuronal =						\
	papers/neuronal/packages.tex					\
	papers/neuronal/main.tex					\
	papers/neuronal/references.bib	

