#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-geostrophisch =						\
	papers/geostrophisch/packages.tex					\
	papers/geostrophisch/main.tex					\
	papers/geostrophisch/references.bib				\
	papers/geostrophisch/teil0.tex					\
	papers/geostrophisch/teil1.tex					\
	papers/geostrophisch/teil2.tex					\
	papers/geostrophisch/teil3.tex

