#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-mongeampere =						\
	papers/mongeampere/packages.tex					\
	papers/mongeampere/main.tex					\
	papers/mongeampere/references.bib				\
	papers/mongeampere/teil0.tex					\
	papers/mongeampere/teil1.tex					\
	papers/mongeampere/teil2.tex					\
	papers/mongeampere/teil3.tex

