#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-parallelisierung =						\
	papers/parallelisierung/packages.tex					\
	papers/parallelisierung/main.tex					\
	papers/parallelisierung/references.bib				\
	papers/parallelisierung/teil0.tex					\
	papers/parallelisierung/teil1.tex					\
	papers/parallelisierung/teil2.tex					\
	papers/parallelisierung/teil3.tex

