#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-parallelisierung =						\
	papers/parallelisierung/packages.tex				\
	papers/parallelisierung/main.tex				\
	papers/parallelisierung/references.bib	

