#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-parallelisierung =						\
	papers/parallelisierung/packages.tex				\
	papers/parallelisierung/main.tex				\
	papers/parallelisierung/Lokalitaet.tex				\
	papers/parallelisierung/Numerische_Methoden.tex			\
	papers/parallelisierung/Gebietsunterteilung.tex			\
	papers/parallelisierung/Parallelisierung.tex			\
	papers/parallelisierung/references.bib	


