#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-helmholtz =						\
	papers/helmholtz/packages.tex					\
	papers/helmholtz/main.tex					\
	papers/helmholtz/references.bib				\
	papers/helmholtz/teil0.tex					\
	papers/helmholtz/teil1.tex					\
	papers/helmholtz/teil2.tex					\
	papers/helmholtz/teil3.tex

