#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fourier =						\
	papers/fourier/packages.tex					\
	papers/fourier/main.tex					\
	papers/fourier/references.bib				\
	papers/fourier/teil0.tex					\
	papers/fourier/teil1.tex					\
	papers/fourier/teil2.tex					\
	papers/fourier/teil3.tex

