#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fourier =						\
	papers/fourier/packages.tex					\
	papers/fourier/main.tex					\
	papers/fourier/references.bib

