#
# Makefile.inc
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/040-green/chapter.tex					\
	chapters/040-green/1-2vektoren.tex				\
	chapters/040-green/2-tensoren.tex				\
	chapters/040-green/3-flaechenintegral.tex			\
	chapters/040-green/4-green.tex					\
	chapters/040-green/5-geschlossen.tex
