#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-diffortho =						\
	papers/diffortho/packages.tex					\
	papers/diffortho/main.tex					\
	papers/diffortho/references.bib				\
	papers/diffortho/teil0.tex					\
	papers/diffortho/teil1.tex					\
	papers/diffortho/teil2.tex

