#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-elastomechanik =						\
	papers/elastomechanik/packages.tex					\
	papers/elastomechanik/main.tex					\
	papers/elastomechanik/references.bib				\
	papers/elastomechanik/teil0.tex					\
	papers/elastomechanik/teil1.tex					\
	papers/elastomechanik/teil2.tex					\
	papers/elastomechanik/teil3.tex

