#
# Makefile
#
# (c) 2025 Prof Dr Andreas Müller
#
all:	faserintegration.pdf homotopie.pdf

faserintegration.pdf:	faserintegration.tex
	pdflatex faserintegration.tex

homotopie.pdf:	homotopie.tex
	pdflatex homotopie.tex

