#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-poinbendix =						\
	papers/poinbendix/packages.tex					\
	papers/poinbendix/main.tex					\
	papers/poinbendix/references.bib				\
	papers/poinbendix/teil0.tex					\
	papers/poinbendix/teil1.tex					\
	papers/poinbendix/teil2.tex					\
	papers/poinbendix/teil3.tex

