#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-poinbendix =						\
	papers/poinbendix/packages.tex					\
	papers/poinbendix/main.tex					\
	papers/poinbendix/references.bib				\
	papers/poinbendix/einleitung.tex					\
	papers/poinbendix/nullklinen.tex					\
	papers/poinbendix/poinbendix.tex					\
	papers/poinbendix/diskussion.tex

