#
# Makefile.inc
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/030-kurvenintegral/fig/fig-1koordinaten.tex		\
	chapters/030-kurvenintegral/fig/fig-loxodrome.tex		\
	chapters/030-kurvenintegral/chapter.tex
