#
# Makefile.inc
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/030-kurvenintegral/fig/fig-1koordinaten.tex		\
	chapters/030-kurvenintegral/fig/fig-loxodrome.tex		\
	chapters/030-kurvenintegral/1-1formen.tex			\
	chapters/030-kurvenintegral/2-kurvenintegral.tex		\
	chapters/030-kurvenintegral/3-differential.tex			\
	chapters/030-kurvenintegral/4-zerlegung.tex			\
	chapters/030-kurvenintegral/chapter.tex
