#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-rossby =						\
	papers/rossby/packages.tex					\
	papers/rossby/main.tex					\
	papers/rossby/references.bib				\

