include papers/4d/Makefile.inc
include papers/elastomechanik/Makefile.inc
include papers/geoalgebra/Makefile.inc
include papers/diffortho/Makefile.inc
include papers/geostrophisch/Makefile.inc
include papers/helmholtz/Makefile.inc
include papers/mongeampere/Makefile.inc
include papers/mongekant/Makefile.inc
include papers/neuronal/Makefile.inc
include papers/openfoam/Makefile.inc
include papers/particles/Makefile.inc
include papers/poinbendix/Makefile.inc
include papers/reaktdiff/Makefile.inc
include papers/reynolds/Makefile.inc
include papers/turing/Makefile.inc
include papers/ueberschall/Makefile.inc

TEXFILES = \
	$(dependencies-4d) \
	$(dependencies-elastomechanik) \
	$(dependencies-geoalgebra) \
	$(dependencies-diffortho) \
	$(dependencies-geostrophisch) \
	$(dependencies-helmholtz) \
	$(dependencies-mongeampere) \
	$(dependencies-mongekant) \
	$(dependencies-neuronal) \
	$(dependencies-openfoam) \
	$(dependencies-particles) \
	$(dependencies-poinbendix) \
	$(dependencies-reaktdiff) \
	$(dependencies-reynolds) \
	$(dependencies-turing) \
	$(dependencies-ueberschall) \

