#
# Makefile
#
# (c) 2025 Prof Dr Andreas Müller
#
all:	1d.pdf 2d.pdf kubisch.pdf linear.pdf

1d.pdf:	1d.tex
	pdflatex 1d.tex

2d.pdf:	2d.tex
	pdflatex 2d.tex

kubisch.pdf:	kubisch.tex
	pdflatex kubisch.tex

linear.pdf:	linear.tex
	pdflatex linear.tex
