#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-schall =						\
	papers/schall/packages.tex					\
	papers/schall/main.tex					\
	papers/schall/references.bib				\
	papers/schall/teil0.tex					\
	papers/schall/teil1.tex					\
	papers/schall/teil2.tex					\
	papers/schall/teil3.tex

