#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-turing =						\
	papers/turing/packages.tex					\
	papers/turing/main.tex					\
	papers/turing/references.bib				\
	papers/turing/teil0.tex					\
	papers/turing/teil1.tex					\
	papers/turing/teil2.tex					\
	papers/turing/teil3.tex

